version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - checkout
    - restore_cache:
        keys:
        - &cache_key v1-intellij-community
    - run: |
        if [ ! -e "$HOME/jdk/bin/javac" ]; then
          curl -vJLO https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-8u222-linux-x64-b1626.3.tar.gz
          mkdir ~/jdk
          tar -xzf jbrsdk*gz -C ~/jdk
          rm jbrsdk*.gz
        fi
        export JAVA_HOME=$HOME/jdk
        PATH=$JAVA_HOME/bin:$PATH
        export JDK_18_x64=$JAVA_HOME
        export JDK_16_x64=$JAVA_HOME
        if [ ! -e android/.git ]; then
            bash -x ./getPlugins.sh
        else
          for d in android android/tools-base; do
            cd $d
            git fetch --all
            git reset --hard origin/master
            cd -
          done
        fi
        ant -debug
    - save_cache:
        when: always
        key: *cache_key
        paths:
        - android/.git
        - android/tools-base/.git
        - ~/.m2
        - ~/.gradle
    - store_artifacts:
        path: out/idea-ce/release/artifacts
